/**
 * Auto-generated TypeScript declarations for Go WASM exports
 * Generated by go-wasm-ts-gen
 */
/**
 * @example
 * // "World"
 * greet()
 * @example
 * // "Go"
 * greet()
 */
declare global {
  interface Window {
    greet(name: string): any;
  }
}
declare global {
  interface Window {
    add(a: number, b: number): any;
  }
}
export {};
