/**
 * Auto-generated TypeScript declarations for Go WASM exports
 * Generated by gowasm-bindgen
 */
interface GetInfoResult {
  name: string;
  active: boolean;
}
/**
 * @example
 * // "World"
 * greet()
 * @example
 * // "Go"
 * greet()
 */
declare global {
  interface Window {
    greet(name: string): string;
  }
  var greet: (name: string) => string;
}
declare global {
  interface Window {
    add(a: number, b: number): number;
  }
  var add: (a: number, b: number) => number;
}
declare global {
  interface Window {
    getInfo(arg0: string): GetInfoResult;
  }
  var getInfo: (arg0: string) => GetInfoResult;
}
export {};
