/**
 * Auto-generated TypeScript declarations for Go WASM exports
 * Generated by gowasm-bindgen
 */
/**
 * @example
 * // "World"
 * greet()
 * @example
 * // "Go"
 * greet()
 */
declare global {
  interface Window {
    greet(name: string): string;
  }
}
declare global {
  interface Window {
    add(a: number, b: number): number;
  }
}
declare global {
  interface Window {
    getInfo(arg0: string): {name: string, active: boolean};
  }
}
export {};
