// client.ts - Generated by gowasm-bindgen --sync
// Package: main

export class Main {
  private constructor() {}

  static async init(wasmSource: string | BufferSource): Promise<Main> {
    const go = new Go();
    let result: WebAssembly.WebAssemblyInstantiatedSource;
    if (typeof wasmSource === 'string') {
      result = await WebAssembly.instantiateStreaming(fetch(wasmSource), go.importObject);
    } else {
      result = await WebAssembly.instantiate(wasmSource, go.importObject);
    }
    void go.run(result.instance);
    return new Main();
  }

  /**
   * GaussianBlur applies Gaussian blur using separable convolution.
   * pixels: RGBA byte array, width/height: image dimensions, radius: blur radius (1-20)
   * Uses fixed-point integer arithmetic for performance.
   */
  gaussianBlur(pixels: Uint8Array, width: number, height: number, radius: number): Uint8Array {
    const result = (globalThis as any).gaussianBlur(pixels, width, height, radius);
    if (result && typeof result === 'object' && '__error' in result) {
      throw new Error((result as { __error: string }).__error);
    }
    return result;
  }

  /**
   * Sharpen applies an unsharp mask sharpening filter.
   * pixels: RGBA byte array, width/height: image dimensions, strength: 1-10
   */
  sharpen(pixels: Uint8Array, width: number, height: number, strength: number): Uint8Array {
    const result = (globalThis as any).sharpen(pixels, width, height, strength);
    if (result && typeof result === 'object' && '__error' in result) {
      throw new Error((result as { __error: string }).__error);
    }
    return result;
  }
}
