// client.ts - Generated by gowasm-bindgen --sync
// Package: main

export interface RunJSResult {
  result: string;
  logs: string;
  errorMsg: string;
}

export class Main {
  private constructor() {}

  static async init(wasmSource: string | BufferSource): Promise<Main> {
    const go = new Go();
    let result: WebAssembly.WebAssemblyInstantiatedSource;
    if (typeof wasmSource === 'string') {
      result = await WebAssembly.instantiateStreaming(fetch(wasmSource), go.importObject);
    } else {
      result = await WebAssembly.instantiate(wasmSource, go.importObject);
    }
    void go.run(result.instance);
    return new Main();
  }

  /**
   * RunJS executes JavaScript code in the Goja interpreter.
   * The __goja__ global is injected to prove execution happens in Goja, not browser JS.
   */
  runJS(code: string): RunJSResult {
    const result = (globalThis as any).runJS(code);
    if (result && typeof result === 'object' && '__error' in result) {
      throw new Error((result as { __error: string }).__error);
    }
    return result;
  }
}
