/**
 * TypeScript declarations for Go WASM runtime (wasm_exec.js)
 * Generated by gowasm-bindgen
 */

declare class Go {
  constructor();
  importObject: WebAssembly.Imports;
  run(instance: WebAssembly.Instance): Promise<number>;
  exited: boolean;
  exitCode: number;
}
